name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infra/docker/tests/Dockerfile
          push: false
          tags: lambda-knowledge-rag:test
          load: true

      - name: Run tests
        run: |
          docker run --rm lambda-knowledge-rag:test uv run tox -e py313

  lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infra/docker/tests/Dockerfile
          push: false
          tags: lambda-knowledge-rag:lint
          load: true

      - name: Run lint
        run: |
          docker run --rm lambda-knowledge-rag:lint uv run tox -e lint

  format-check:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infra/docker/tests/Dockerfile
          push: false
          tags: lambda-knowledge-rag:format
          load: true

      - name: Check formatting
        run: |
          docker run --rm lambda-knowledge-rag:format uv run tox -e format-check
