name: CI — tox via Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build Docker test image and run tox
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build test image (uses src/docker/tests/Dockerfile)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: src/docker/tests/Dockerfile
          push: false
          tags: lambda-knowledge-rag:ci

      - name: Run tests in Docker
        run: |
          docker run --rm lambda-knowledge-rag:ci
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: pytest -q
